/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Budget } from "./Budget";
import { BudgetCountArgs } from "./BudgetCountArgs";
import { BudgetFindManyArgs } from "./BudgetFindManyArgs";
import { BudgetFindUniqueArgs } from "./BudgetFindUniqueArgs";
import { CreateBudgetArgs } from "./CreateBudgetArgs";
import { UpdateBudgetArgs } from "./UpdateBudgetArgs";
import { DeleteBudgetArgs } from "./DeleteBudgetArgs";
import { ExpenseFindManyArgs } from "../../expense/base/ExpenseFindManyArgs";
import { Expense } from "../../expense/base/Expense";
import { User } from "../../user/base/User";
import { BudgetService } from "../budget.service";
@graphql.Resolver(() => Budget)
export class BudgetResolverBase {
  constructor(protected readonly service: BudgetService) {}

  async _budgetsMeta(
    @graphql.Args() args: BudgetCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Budget])
  async budgets(@graphql.Args() args: BudgetFindManyArgs): Promise<Budget[]> {
    return this.service.budgets(args);
  }

  @graphql.Query(() => Budget, { nullable: true })
  async budget(
    @graphql.Args() args: BudgetFindUniqueArgs
  ): Promise<Budget | null> {
    const result = await this.service.budget(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Budget)
  async createBudget(@graphql.Args() args: CreateBudgetArgs): Promise<Budget> {
    return await this.service.createBudget({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Budget)
  async updateBudget(
    @graphql.Args() args: UpdateBudgetArgs
  ): Promise<Budget | null> {
    try {
      return await this.service.updateBudget({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Budget)
  async deleteBudget(
    @graphql.Args() args: DeleteBudgetArgs
  ): Promise<Budget | null> {
    try {
      return await this.service.deleteBudget(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Expense], { name: "expenses" })
  async findExpenses(
    @graphql.Parent() parent: Budget,
    @graphql.Args() args: ExpenseFindManyArgs
  ): Promise<Expense[]> {
    const results = await this.service.findExpenses(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  async getUser(@graphql.Parent() parent: Budget): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
